-- =============================================================================
-- SEED — volontairement vide
-- Les données de démonstration se chargent depuis l'app pour l'utilisateur connecté.
-- Recréé automatiquement à chaque `supabase db reset`
-- =============================================================================
